### PR TITLE
Added the ability to render multiple SVGs in one go

### PR DESCRIPTION
**Pull request by dxprog**
Helping mitigate the perf overhead of batch conversions by adding the ability to handle multiple files in one request. Also addressed an issue where my machine was generating different but visually identical PNGs. All tests and docs have been updated and linting passes.

### CODE REVIEW

**Comment by domenic** [comment]
I'm sorry, this is too much of a change for me to accept. I prefer simple modules that are easy to compose with language constructs (like `for` loops) to do the same thing multiple times, instead of building that into the module.

Perhaps you could come up with a simpler modification to the API that would help avoid the performance overhead? E.g., passing in a reusable "session" object as an option?

**Comment by dxprog** [comment]
Nah, I'll fust fork it and rebrand. I brought render times down from 15 minutes (on a simple for loop) to 2 minutes, so it definitely has merit.

**Comment by domenic** [comment]
Sounds good! Let me know what it gets published as and I can link to it in the readme.

**Comment by jimmyhchan** [comment]
@dxprog  have you seen https://github.com/defunctzombie/svg2png    in particular the one commit to re-use the phantom process https://github.com/defunctzombie/svg2png/commit/30a8274b46397def69c2bc3684ffd9da85b1dd3b

**Pull request closed without merging**
