### PR TITLE
Add scale object argument (with tests and fixes)

### PR DESCRIPTION
**Pull request by kasbah**
The tests will only pass on Linux due to #9.

### CODE REVIEW

**Comment by domenic** [comment]
Thank you very much! No worries about the tests; I will rebase them to work on Windows.

A couple issues:

- I think it would be best to not support the "XxY" string version, and just the object version. This removes some code complexity (where we convert objects to strings and then back to objects). There are also no tests for the "XxY" syntax so that saves some work there :)
- As you mention, the image will be centered and zoomed, but not stretched. As such the word "scale" seems wrong. (Although it only shows up in the code and commit messages.) Maybe "dimensions" would be better.

**Comment by kasbah** [comment]
- I thought we _have_ to convert objects to strings and back to objects because we are going through execFile. Is that not the case? That you can actually use a string directly as an argument was a mistake, though not sure what disallowing it would give us. 
- Do you want me to change 'scale' to 'dimensions' everywhere? The problem is there is a lot of re-use of the same variables between the two usages.

**Comment by kasbah** [comment]
Also, it still scales the image, just uniformly.

**Comment by domenic** [comment]
> I thought we have to convert objects to strings and back to objects because we are going through execFile.

Ah I see, you're right. Well, instead of custom serialization and deserialization logic, let's just use JSON.stringify.

> Do you want me to change scale to dimensions everywhere? The problem is there is a lot of re-use of the same variables between the two usages. 

Yes please. The numbers provided are not a scale (like 1.0, or 1.5, or whatever) but instead are dimensions.

**Comment by kasbah** [comment]
I renamed the argument to `resize` and replaced the custom serialization with JSON functions.

**Comment by kasbah** [comment]
Would be really great if this could be merged and released, if everything is ok, so I can get rid of a submodule in a project of mine.

**Comment by domenic** [comment]
Thanks so much for this work and sorry for the delay. Merged as 62ec7fae7dc40a7fbe87e314cf8a41c7cc340c5d and I will do a new release within the hour.

**Pull request closed without merging**
